print("walk past parking lot 102 towards Olsen Blvd")
print("turn right onto Corrington Drive")
print("slight left around wcg building")
print("head towards msc")
print("walk between hart and ssb")
print("walk towards bltn building")
print("turn right at edct building and walk towards chem bilding")
print("walk straight")
print("turn right onto spence street")
print("building should be on the right")
print("as you enter the building, take the staircase on the left and continue to the fourth floor")
print("go to the 24th room")
print("arriving at destination")


print("Matthew Strode Comments- Straight forward, easy to follow")
print("Jackson Hosea Comments- Looks good! Pretty straightforward and easy to follow.")
print ("Jennyfer Hoang Comments- very nice! short and sweet!")